sudo: required
language: java
jdk: openjdk11

before_install:
  - chmod +x mvnw

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

stages:
  - build
  - docker_image
  - deploy

jobs:
  include:
    - stage: build
      script: mvn clean -B package
    - stage: docker_image
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export TAG=latest
        - export IMAGE_NAME=feliperosadr/java-spring-microservice
        - docker build -t $IMAGE_NAME:$COMMIT .
        - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
        - docker push $IMAGE_NAME
    - stage: deploy
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: java-spring-microservice
