sudo: required
language: java
jdk: openjdk11

before_install:
  - chmod +x mvnw
  -
services:
  - docker

stages:
  - build
  - docker_image
  - deploy

jobs:
  include:
    - stage: build
      script: mvn clean -B package
    - stage: docker_image
      script:
        - docker-compose build

