server:
  port: 8083
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/sample'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
